### PR TITLE
we added some cute little improvement

### PR DESCRIPTION
**Pull request by towgenik**
+ Update it to work with 1.17.1
+ Simple Sierra 2-4A Dithering/FilterLiteDither
+ Config file to change resolution
+ Data file to automatically load maps at startup
+ Multithreading
+ maps now are in sync
+ fix choppy image output
- Remove Herobrine

### CODE REVIEW

**Comment by makinori** [comment]
Wow! that's a huge pr for something I was just experimenting with a long time ago! If you'd like, I can just add you as a contributor and we can change the name and commands to something better than my name

**Comment by makinori** [comment]
I added a github actions workflow for building, caching and artifacting on push so there's always a .jar available for people to download

**Comment by towgenik** [comment]
Thank you for accepting our PR

**Comment by towgenik** [comment]
>and we can change the name and commands to something better than my name

I'm sorry, but I'm not that good at naming things. I might give it a more specific name, like OBSScreen or MapsStreamer. but in my opinion, the name MakiScreen is somewhat stuck in my head, so IDK ¯\\_(ツ)_/¯

**Pull request merged**
